<?php
// Generated by klodian , In this file must set all api routing ..................................
// set all shopping routes ......
route::department('/shopping')->routes( function() {

    route::group('/header')->routes( function() {

        route::get('/language','languages@get_language');

        route::get('/change_language','languages@change_language');

        route::post('/delete_items_inWish','header@delete_from_wishlist');

        route::post('/delete_items_inCart','header@delete_from_cartlist');

        route::post('/update_cartList','header@update_cartList');

        route::post('/add_inwishList','header@add_wish_cookie');

        route::post('/add_incartList','header@add_cart_cookie');

        route::get('/wishList_cartList','header@get_wishlist_cartList');

        route::get('/search','search@search_in_header');
    });

    route::group('/menu')->routes( function() {

        route::get('/category','menu@get_category');

    });

    route::group('/login_register')->routes( function() {

        route::get('/auth','auth@set_token');

        route::get('/check','auth@check_token');

    });

    route::group('/home')->routes( function() {

        route::get('/categories','home@get_categories');

        route::get('/more_products_incarousel','home@more_products');

    });

    route::group('/products')->routes( function() {

        route::get('/category_products','products@getproducts');

        route::get('/product_details','products@get_product_details');

        route::get('/change_products_forpage','products@chnageProductsForPage');

    });

    route::group('/company')->routes( function() {

        route::get('/check','supplier@check');

        route::get('/home','supplier@home');


    });

    route::group('/settings')->routes( function() {

        route::get('/menu','settings@get_settings');
         route::get('/change_menu','settings@change_menu');

    });

});

// set all company routes ...
route::department('/company')->routes( function(){

    route::group('/menu')->routes( function() {

        route::get('/f','languages@get_language');

        route::get('/register','auth@register');

    });
});

route::department('')->routes( function(){  // start server without any path or uri ....

    route::get('/','index@wellcome');

});


route::finished(); // if don't match any route display a throw error


?>