<?php

 use server\services\auth\auth as auth; // use auth service autoload it automatically when it is required

 auth::check_auth() ? auth::check_token() : false ; // check if token and client signature are in request header
  // check if token has expired return 403 status error and  automatically will come a new request to refresh it
  // check token if is correctly save user details in auth service then controllers can use it if needed ..........

  // Generated by klodian , In this file must set all api routing ..................................
  // set all shopping routes ......
 route::department('/shopping')->routes( function() {

     route::group('/client')->routes( function() {
         // security route need Authorized to execute or error Unauthorized ....
         route::get('/load_client','client@load_client')->auth()->exe();
     });

     route::group('/auth')->routes( function() {

         route::post('/credentials','client_auth@login')->exe();

         route::post('/register_user','client_auth@register')->exe();

         route::get('/refresh_token','client_auth@refresh_token')->exe();

         route::post('/check_supplier','client_auth@check_supplier')->exe();
     });

     route::group('/header')->routes( function(){

         route::get('','header@load_header')->exe(); // load all data that need header ...................

         route::get('/language','header@get_language')->exe();

         route::get('/change_language','header@change_language')->exe();

         route::post('/delete_items_inWish','header@delete_from_wishlist')->exe();

         route::get('/wishList_cartList','header@get_wishlist_cartList')->exe();

         route::post('/delete_items_inCart','header@delete_from_cartlist')->exe();

         route::post('/update_cartList','header@update_cartList')->exe();

         route::post('/add_inwishList','header@add_wish_cookie')->exe();

         route::post('/add_incartList','header@add_cart_cookie')->exe();

         route::get('/search','search@search_in_header')->exe();
     });

     route::group('/menu')->routes( function() {

         route::get('/category','menu@get_category')->exe();
     });

     route::group('/login_register')->routes( function() {

         route::get('/clientAuth','clientAuth@set_token')->exe();

         route::get('/check','clientAuth@check_token')->exe();
     });

     route::group('/home')->routes( function() {

         route::get('/categories','home@get_categories')->exe();

         route::get('/more_products_incarousel','home@more_products')->exe();
     });

     route::group('/products')->routes( function() {

         route::get('/category_products','products@getproducts')->exe();

         route::get('/product_details','products@get_product_details')->exe();

         route::get('/change_products_forpage','products@chnageProductsForPage')->exe();
     });

     route::group('/company')->routes( function() {

         route::get('/check','supplier@check')->exe();

         route::get('/home','supplier@home')->exe();
     });

     route::group('/settings')->routes( function() {

         route::get('/menu','settings@get_settings')->exe();

         route::get('/change_menu','settings@change_menu')->exe();
     });
 });

  // set all company routes ...
 route::department('/company')->routes( function(){

     route::group('/menu')->routes( function() {

         route::get('/f','languages@get_language')->exe();

         route::get('/register','clientAuth@register')->exe();
     });
 });

 route::department('')->routes( function(){  // start server without any path or uri ....

     route::get('/','index@wellcome')->exe();
 });

 route::finished(); // if don't match any route display a throw error


?>