<?php
// Generated by klodian , In this file must set all api routing ..................................


Route::department('/shopping')->routes( function() {

    Route::group('/header')->routes( function() {

        Route::get('/language','Language_con@get_language');

        Route::get('/change_language','Language_con@change_language');

        Route::post('/delete_items_inWish','Header@delete_from_wishlist');

        Route::post('/delete_items_inCart','Header@delete_from_cartlist');

        Route::get('/update_cartList','Header@update_cartList');

        Route::get('/add_inwishList','Header@Header@add_wish_cookie');

        Route::get('/add_incartList','Header@Header@add_cart_cookie');

        Route::get('/wishList_cartList','Header@get_wishlist_cartList');

        Route::get('/search','Search@get_search_results');
    });

    Route::group('/menu')->routes( function() {

        Route::get('/category','Menu@get_category');

    });

    Route::group('/home')->routes( function() {

        Route::get('/categories','Home@get_categories');

        Route::get('/more_products_incarousel','Home@more_products');

    });

    Route::group('/products')->routes( function() {

        Route::get('/category_products','Products@getproducts');

        Route::get('/products_details','Home@more_products');

        Route::get('/change_products_forpage','Products@chnageProductsForPage');

    });

    Route::group('/company')->routes( function() {

        Route::get('/load','Company@load_company');

        Route::get('/categories','Home@get_categories');

        Route::get('/more_products_incarousel','Home@more_products');
    });
});
Route::department('/company')->routes( function(){

    Route::group('/menu')->routes( function() {

        Route::get('/f','Language_con@get_language');

        Route::get('/register','Auth@register');

    });
});

Route::finished(); // if don't match any route display a throw error

?>