<?php

namespace server\files ;

    include '../connection_db/class_connection.php'; // include connection with database and that have some method to access db ................

    include '../Fetch_Data/Fetch_Data.php'; // include fetch data file  ..............................

    include '../Auth/Auth_Register.php'; // include Auth_register_user  to  access their account .........................

    include '../Category_Subscribe_and_Products/Category_Subscribe.php'; // include category and subscribe  ...................................

    include '../Products/Products.php';  // include  products file .......................................

    include '../Session_Cookie/Cookies.php'; // include cookie class ............

    include '../Language/language.php'; // include language class..............



?>