<?php
require('class_connection.php'); // include class connection ......................................

class search extends connection{ // class search ectends from connection ......................

    public function searchcompany($valu){

		$sql="SELECT id , name_company,imageprofile from adminat where name_company LIKE '%".$valu."%'"; // variable with sql .....................

		$getrow=self::run_query($sql); // call methos run_query ...............................
        $i=0;
        $ret = array(); // array
        while ($row = mysqli_fetch_assoc($getrow)) { // fetch row  from db.....................
              foreach ($row as $key => $value) { //  data as row ................................
                      $ret[$i][$key] = $value; // build array ...............................
              }
              $i++;
        }
        return ($ret); // return array........................

    }
}

$search = new search(); // new object that call method in class search .............................

if(isset($_GET['searchsubscribe']) && !empty($_GET['searchsubscribe']) && isset($_GET['control'])){ // check is  exist  variable searchsubscribe and it not is null ..........................
   
    $control=$_GET['control']; //  controcl value .......................

	if($control=='search12'){ // check if controll is with this value .................................
	     $res_array=$search->searchcompany($_GET['searchsubscribe']); // call method searchcompany........................
	     $json = json_encode($res_array); //  from array to json encode .........................
	     echo $json; // echo result json .....................
     }
}
?>
