<?php

// Generated by klodian , In this file must set all api routing ..................................

Route::get('/menu' ,'Menu@get_category');

Route::get('/wishList_cartList' ,'Header@get_wishlist_cartList');

Route::get('/language' ,'Language_con@get_language');

Route::get('/changeLanguage' ,'Language_con@change_language');

Route::get('/products','Products@getproducts');

Route::get('/product_details','Products@get_product_details');

Route::get('/categories_products' ,'Home@get_categories');

Route::get('/moreProductsInCategory','Home@more_products');

Route::post('/addInWishList','Header@add_wish_cookie');

Route::post('/addInCartList' ,'Header@add_cart_cookie');

Route::post('/deleteItemsInWish' ,'Header@delete_from_wishlist');

Route::post('/deleteItemsInCart' ,'Header@delete_from_cartlist');

Route::post('/auth' ,'Auth@checkUser');

Route::get('/searchProducts','Products@search');

Route::get('/getSettings' ,'Settings@get_settings' );

Route::get('/settingMenu' ,'Settings@menu' );


?>